# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: docker_publish

# Controls when the action will run.
on: 
  - push
  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Docker meta plugindatareader
        id: meta_plugindatareader
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/plugindatareader,ghcr.io/${{ github.repository_owner }}/plugindatareader
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}
            prefix=
            suffix=

      # Create a Access Token and save it as as Actions secret
      # https://hub.docker.com/settings/security
      # DOCKERHUB_USERNAME
      # DOCKERHUB_TOKEN
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Create a Access Token with `read:packages` and `write:packages` scopes
      # CR_PAT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push PluginDataReader
        uses: docker/build-push-action@v2
        with:
          context: .
          file: PluginDataReader/Dockerfile
          push: true
          tags: ${{ steps.meta_plugindatareader.outputs.tags }}
          labels: ${{ steps.meta_plugindatareader.outputs.labels }}

